# Generated by Django 5.2.3 on 2025-06-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[("IT", "IT"), ("HR", "HR"), ("Sales", "Sales")],
                        max_length=50,
                    ),
                ),
                ("level", models.CharField(max_length=50)),
                ("area", models.CharField(max_length=100)),
            ],
        ),
    ]
