# Generated by Django 5.2.3 on 2025-06-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="skill",
            old_name="area",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="level",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="name",
        ),
        migrations.AlterField(
            model_name="skill",
            name="category",
            field=models.CharField(max_length=50),
        ),
    ]
