# Generated by Django 5.2.3 on 2025-06-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("skills", "0002_category_subcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="level",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="skill",
            name="subcategory",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
